name: Main
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/docs'
      - 'mkdocs.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      packages: write
      # release please needs write for contents and pr
      contents: write
      pull-requests: write
    steps:
      - name: Dump context for debugging
        if: ${{ true }}
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      # This will possibly
      #  a) update the pending release PR; or
      #  b) (if this commit is from merging the pending release PR) create a release tag and release
      #
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4
        id: release
        with:
          target-branch: main

      - name: Dump output from release-please for debugging
        if: ${{ true }}
        run: |
          echo "$RELEASE_PLEASE_OUTPUT"
        env:
          RELEASE_PLEASE_OUTPUT: ${{ toJson(steps.release.outputs) }}

      # Check out the tag ref "refs/tags/v1.2.3" if a release tag was just created.
      # Later docker meta will derive image tags from that.
      #
      - name: Checkout code from tag
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
        with:
          ref: ${{ steps.release.outputs.tag_name }}

      - name: Checkout code from workflow
        if: ${{ ! steps.release.outputs.release_created }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4

      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v4
        with:
          node-version: 24

      - name: Install dependencies with audit
        run: |
          npm ci
          npm audit check --omit=dev --audit-level=high
          npm run lint
          npm run build

      - name: Run tests
        run: npm run test

      - name: Build and push docker
        id: docker
        uses: ./.github/actions/docker-build
        with:
          labels: |
            org.opencontainers.image.title=Otel Demo
            org.opencontainers.image.description=Nest.Js with OTEL and other random experimentation
          github-token: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ steps.release.outputs.release_created && 'git' || 'workflow' }}
          # Add workflow ref name (e.g. main) so name (main) is included in image tags
          raw-tags: ${{ steps.release.outputs.release_created && github.ref_name || '' }}
        env:
          DOCKER_BUILDKIT: 1

      - name: Parse Meta
        id: parse-meta
        env:
          DOCKER_METADATA: ${{ steps.docker.outputs.docker-metadata }}
        run: |
          IMAGE_LIST=$(echo "$DOCKER_METADATA" | jq -r '.["image.name"]' | tr ',' '\n')
          {
            echo 'images<<EOF'
            echo "$IMAGE_LIST"
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Update release
        if: ${{ steps.release.outputs.tag_name }}
        id: update_release
        uses: tubone24/update_release@c04c17054b939144ec8a7cba969d74992f812d66 # v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
        with:
          is_append_body: true
          body: |

            ### Container Images

             ```text
            ${{ steps.parse-meta.outputs.images }}
            ```

            Metadata:

            ```json
            ${{ steps.docker.outputs.docker-metadata }}
            ```
